config/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

""" urlpatterns = [
    path('', views.index, name='index'),
    path('<int:itemspec_list_id>/', views.detail, name='detail'),
]  """

config/config/urls.py
from django.contrib import admin
from django.urls import path, include 
from heatpipe import views   
from django.contrib.auth import views as auth_views

# urlpatterns = [
#     path('admin/', admin.site.urls),
#     path('common/', include('common.urls')),
#     path('heatpipe/', include('heatpipe.urls')), 
#     path('', views.index, name='index'),  # '/' 에 해당되는 path
# ]
 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('common/', include('common.urls')),  
    path('heatpipe/', include('heatpipe.urls')),     
    path('', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
]

config/heatpipe/urls.py
from django.urls import path

from . import views

app_name = 'heatpipe'

urlpatterns = [
    # path('', views.index, name='index'),
    path('', views.index, name='index'),
    path('<int:itemspec_list_id>/', views.detail, name='detail'),
] 

config/templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title> Daehong Heatpipe Performance List </title>
</head>
<body> 
    <!-- 네비게이션바 --> 
    <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
        <div class="container-fluid">
            <!-- <a class="navbar-brand" href="{% url 'heatpipe:index' %}">Daehong Heatpipe</a> -->
            <button class="navbar-toggler" type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent"
                    aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item"> 
                        {% if user.is_authenticated %}
                        <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
                        {% else %}
                        <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                        {% endif %}
                    </li>
                </ul>
            </div>
        </div>
    </nav>

<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End --> 
</body>
</html>
 

config/templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

config/templates/navbar.html
<li class="nav-item">
    {% if user.is_authenticated %}
    <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
    {% else %}
    <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
    {% endif %}
</li>